[tool.poetry]
name = "mahjong"
version = "0.1.0"
description = ""
authors = ["thgwon-yaho-qcw <gwontaeho96@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^6.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
